// Code generated by Kitex v0.4.4. DO NOT EDIT.

package helloservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	hello "kitex-ex/kitex_gen/hello"
)

func serviceInfo() *kitex.ServiceInfo {
	return helloServiceServiceInfo
}

var helloServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "HelloService"
	handlerType := (*hello.HelloService)(nil)
	methods := map[string]kitex.MethodInfo{
		"echo":           kitex.NewMethodInfo(echoHandler, newHelloServiceEchoArgs, newHelloServiceEchoResult, false),
		"testHello4Get":  kitex.NewMethodInfo(testHello4GetHandler, newHelloServiceTestHello4GetArgs, newHelloServiceTestHello4GetResult, false),
		"testHello4Post": kitex.NewMethodInfo(testHello4PostHandler, newHelloServiceTestHello4PostArgs, newHelloServiceTestHello4PostResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "hello",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

func echoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*hello.HelloServiceEchoArgs)
	realResult := result.(*hello.HelloServiceEchoResult)
	success, err := handler.(hello.HelloService).Echo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newHelloServiceEchoArgs() interface{} {
	return hello.NewHelloServiceEchoArgs()
}

func newHelloServiceEchoResult() interface{} {
	return hello.NewHelloServiceEchoResult()
}

func testHello4GetHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*hello.HelloServiceTestHello4GetArgs)
	realResult := result.(*hello.HelloServiceTestHello4GetResult)
	success, err := handler.(hello.HelloService).TestHello4Get(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newHelloServiceTestHello4GetArgs() interface{} {
	return hello.NewHelloServiceTestHello4GetArgs()
}

func newHelloServiceTestHello4GetResult() interface{} {
	return hello.NewHelloServiceTestHello4GetResult()
}

func testHello4PostHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*hello.HelloServiceTestHello4PostArgs)
	realResult := result.(*hello.HelloServiceTestHello4PostResult)
	success, err := handler.(hello.HelloService).TestHello4Post(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newHelloServiceTestHello4PostArgs() interface{} {
	return hello.NewHelloServiceTestHello4PostArgs()
}

func newHelloServiceTestHello4PostResult() interface{} {
	return hello.NewHelloServiceTestHello4PostResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Echo(ctx context.Context, req *hello.Request) (r *hello.Response, err error) {
	var _args hello.HelloServiceEchoArgs
	_args.Req = req
	var _result hello.HelloServiceEchoResult
	if err = p.c.Call(ctx, "echo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) TestHello4Get(ctx context.Context, req *hello.Request) (r *hello.Response, err error) {
	var _args hello.HelloServiceTestHello4GetArgs
	_args.Req = req
	var _result hello.HelloServiceTestHello4GetResult
	if err = p.c.Call(ctx, "testHello4Get", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) TestHello4Post(ctx context.Context, req *hello.Request) (r *hello.Response, err error) {
	var _args hello.HelloServiceTestHello4PostArgs
	_args.Req = req
	var _result hello.HelloServiceTestHello4PostResult
	if err = p.c.Call(ctx, "testHello4Post", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
