// Code generated by Kitex v0.4.4. DO NOT EDIT.

package hello2service

import (
	"context"
	"fmt"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
	hello2 "kitex-ex/kitex_gen/hello2"
)

func serviceInfo() *kitex.ServiceInfo {
	return hello2ServiceServiceInfo
}

var hello2ServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "Hello2Service"
	handlerType := (*hello2.Hello2Service)(nil)
	methods := map[string]kitex.MethodInfo{
		"ClientSideStreaming": kitex.NewMethodInfo(clientSideStreamingHandler, newClientSideStreamingArgs, newClientSideStreamingResult, false),
		"ServerSideStreaming": kitex.NewMethodInfo(serverSideStreamingHandler, newServerSideStreamingArgs, newServerSideStreamingResult, false),
		"BidiSideStreaming":   kitex.NewMethodInfo(bidiSideStreamingHandler, newBidiSideStreamingArgs, newBidiSideStreamingResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "hello2",
	}
	extra["streaming"] = true
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

func clientSideStreamingHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	st := arg.(*streaming.Args).Stream
	stream := &hello2ServiceClientSideStreamingServer{st}
	return handler.(hello2.Hello2Service).ClientSideStreaming(stream)
}

type hello2ServiceClientSideStreamingClient struct {
	streaming.Stream
}

func (x *hello2ServiceClientSideStreamingClient) Send(m *hello2.Request) error {
	return x.Stream.SendMsg(m)
}
func (x *hello2ServiceClientSideStreamingClient) CloseAndRecv() (*hello2.Response, error) {
	if err := x.Stream.Close(); err != nil {
		return nil, err
	}
	m := new(hello2.Response)
	return m, x.Stream.RecvMsg(m)
}

type hello2ServiceClientSideStreamingServer struct {
	streaming.Stream
}

func (x *hello2ServiceClientSideStreamingServer) SendAndClose(m *hello2.Response) error {
	return x.Stream.SendMsg(m)
}

func (x *hello2ServiceClientSideStreamingServer) Recv() (*hello2.Request, error) {
	m := new(hello2.Request)
	return m, x.Stream.RecvMsg(m)
}

func newClientSideStreamingArgs() interface{} {
	return &ClientSideStreamingArgs{}
}

func newClientSideStreamingResult() interface{} {
	return &ClientSideStreamingResult{}
}

type ClientSideStreamingArgs struct {
	Req *hello2.Request
}

func (p *ClientSideStreamingArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(hello2.Request)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *ClientSideStreamingArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *ClientSideStreamingArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *ClientSideStreamingArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in ClientSideStreamingArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *ClientSideStreamingArgs) Unmarshal(in []byte) error {
	msg := new(hello2.Request)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ClientSideStreamingArgs_Req_DEFAULT *hello2.Request

func (p *ClientSideStreamingArgs) GetReq() *hello2.Request {
	if !p.IsSetReq() {
		return ClientSideStreamingArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ClientSideStreamingArgs) IsSetReq() bool {
	return p.Req != nil
}

type ClientSideStreamingResult struct {
	Success *hello2.Response
}

var ClientSideStreamingResult_Success_DEFAULT *hello2.Response

func (p *ClientSideStreamingResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(hello2.Response)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *ClientSideStreamingResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *ClientSideStreamingResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *ClientSideStreamingResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in ClientSideStreamingResult")
	}
	return proto.Marshal(p.Success)
}

func (p *ClientSideStreamingResult) Unmarshal(in []byte) error {
	msg := new(hello2.Response)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ClientSideStreamingResult) GetSuccess() *hello2.Response {
	if !p.IsSetSuccess() {
		return ClientSideStreamingResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ClientSideStreamingResult) SetSuccess(x interface{}) {
	p.Success = x.(*hello2.Response)
}

func (p *ClientSideStreamingResult) IsSetSuccess() bool {
	return p.Success != nil
}

func serverSideStreamingHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	st := arg.(*streaming.Args).Stream
	stream := &hello2ServiceServerSideStreamingServer{st}
	req := new(hello2.Request)
	if err := st.RecvMsg(req); err != nil {
		return err
	}
	return handler.(hello2.Hello2Service).ServerSideStreaming(req, stream)
}

type hello2ServiceServerSideStreamingClient struct {
	streaming.Stream
}

func (x *hello2ServiceServerSideStreamingClient) Recv() (*hello2.Response, error) {
	m := new(hello2.Response)
	return m, x.Stream.RecvMsg(m)
}

type hello2ServiceServerSideStreamingServer struct {
	streaming.Stream
}

func (x *hello2ServiceServerSideStreamingServer) Send(m *hello2.Response) error {
	return x.Stream.SendMsg(m)
}

func newServerSideStreamingArgs() interface{} {
	return &ServerSideStreamingArgs{}
}

func newServerSideStreamingResult() interface{} {
	return &ServerSideStreamingResult{}
}

type ServerSideStreamingArgs struct {
	Req *hello2.Request
}

func (p *ServerSideStreamingArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(hello2.Request)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *ServerSideStreamingArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *ServerSideStreamingArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *ServerSideStreamingArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in ServerSideStreamingArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *ServerSideStreamingArgs) Unmarshal(in []byte) error {
	msg := new(hello2.Request)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ServerSideStreamingArgs_Req_DEFAULT *hello2.Request

func (p *ServerSideStreamingArgs) GetReq() *hello2.Request {
	if !p.IsSetReq() {
		return ServerSideStreamingArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ServerSideStreamingArgs) IsSetReq() bool {
	return p.Req != nil
}

type ServerSideStreamingResult struct {
	Success *hello2.Response
}

var ServerSideStreamingResult_Success_DEFAULT *hello2.Response

func (p *ServerSideStreamingResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(hello2.Response)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *ServerSideStreamingResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *ServerSideStreamingResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *ServerSideStreamingResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in ServerSideStreamingResult")
	}
	return proto.Marshal(p.Success)
}

func (p *ServerSideStreamingResult) Unmarshal(in []byte) error {
	msg := new(hello2.Response)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ServerSideStreamingResult) GetSuccess() *hello2.Response {
	if !p.IsSetSuccess() {
		return ServerSideStreamingResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ServerSideStreamingResult) SetSuccess(x interface{}) {
	p.Success = x.(*hello2.Response)
}

func (p *ServerSideStreamingResult) IsSetSuccess() bool {
	return p.Success != nil
}

func bidiSideStreamingHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	st := arg.(*streaming.Args).Stream
	stream := &hello2ServiceBidiSideStreamingServer{st}
	return handler.(hello2.Hello2Service).BidiSideStreaming(stream)
}

type hello2ServiceBidiSideStreamingClient struct {
	streaming.Stream
}

func (x *hello2ServiceBidiSideStreamingClient) Send(m *hello2.Request) error {
	return x.Stream.SendMsg(m)
}
func (x *hello2ServiceBidiSideStreamingClient) Recv() (*hello2.Response, error) {
	m := new(hello2.Response)
	return m, x.Stream.RecvMsg(m)
}

type hello2ServiceBidiSideStreamingServer struct {
	streaming.Stream
}

func (x *hello2ServiceBidiSideStreamingServer) Send(m *hello2.Response) error {
	return x.Stream.SendMsg(m)
}

func (x *hello2ServiceBidiSideStreamingServer) Recv() (*hello2.Request, error) {
	m := new(hello2.Request)
	return m, x.Stream.RecvMsg(m)
}

func newBidiSideStreamingArgs() interface{} {
	return &BidiSideStreamingArgs{}
}

func newBidiSideStreamingResult() interface{} {
	return &BidiSideStreamingResult{}
}

type BidiSideStreamingArgs struct {
	Req *hello2.Request
}

func (p *BidiSideStreamingArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(hello2.Request)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *BidiSideStreamingArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *BidiSideStreamingArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *BidiSideStreamingArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in BidiSideStreamingArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *BidiSideStreamingArgs) Unmarshal(in []byte) error {
	msg := new(hello2.Request)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var BidiSideStreamingArgs_Req_DEFAULT *hello2.Request

func (p *BidiSideStreamingArgs) GetReq() *hello2.Request {
	if !p.IsSetReq() {
		return BidiSideStreamingArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *BidiSideStreamingArgs) IsSetReq() bool {
	return p.Req != nil
}

type BidiSideStreamingResult struct {
	Success *hello2.Response
}

var BidiSideStreamingResult_Success_DEFAULT *hello2.Response

func (p *BidiSideStreamingResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(hello2.Response)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *BidiSideStreamingResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *BidiSideStreamingResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *BidiSideStreamingResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in BidiSideStreamingResult")
	}
	return proto.Marshal(p.Success)
}

func (p *BidiSideStreamingResult) Unmarshal(in []byte) error {
	msg := new(hello2.Response)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *BidiSideStreamingResult) GetSuccess() *hello2.Response {
	if !p.IsSetSuccess() {
		return BidiSideStreamingResult_Success_DEFAULT
	}
	return p.Success
}

func (p *BidiSideStreamingResult) SetSuccess(x interface{}) {
	p.Success = x.(*hello2.Response)
}

func (p *BidiSideStreamingResult) IsSetSuccess() bool {
	return p.Success != nil
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ClientSideStreaming(ctx context.Context) (Hello2Service_ClientSideStreamingClient, error) {
	streamClient, ok := p.c.(client.Streaming)
	if !ok {
		return nil, fmt.Errorf("client not support streaming")
	}
	res := new(streaming.Result)
	err := streamClient.Stream(ctx, "ClientSideStreaming", nil, res)
	if err != nil {
		return nil, err
	}
	stream := &hello2ServiceClientSideStreamingClient{res.Stream}
	return stream, nil
}

func (p *kClient) ServerSideStreaming(ctx context.Context, req *hello2.Request) (Hello2Service_ServerSideStreamingClient, error) {
	streamClient, ok := p.c.(client.Streaming)
	if !ok {
		return nil, fmt.Errorf("client not support streaming")
	}
	res := new(streaming.Result)
	err := streamClient.Stream(ctx, "ServerSideStreaming", nil, res)
	if err != nil {
		return nil, err
	}
	stream := &hello2ServiceServerSideStreamingClient{res.Stream}
	if err := stream.Stream.SendMsg(req); err != nil {
		return nil, err
	}
	if err := stream.Stream.Close(); err != nil {
		return nil, err
	}
	return stream, nil
}

func (p *kClient) BidiSideStreaming(ctx context.Context) (Hello2Service_BidiSideStreamingClient, error) {
	streamClient, ok := p.c.(client.Streaming)
	if !ok {
		return nil, fmt.Errorf("client not support streaming")
	}
	res := new(streaming.Result)
	err := streamClient.Stream(ctx, "BidiSideStreaming", nil, res)
	if err != nil {
		return nil, err
	}
	stream := &hello2ServiceBidiSideStreamingClient{res.Stream}
	return stream, nil
}
