// Code generated by Kitex v0.4.4. DO NOT EDIT.
package hello2service

import (
	server "github.com/cloudwego/kitex/server"
	hello2 "kitex-ex/kitex_gen/hello2"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler hello2.Hello2Service, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
